name: deploy-on-push

on: 
  push:
    branches:
      - main

jobs:
  deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: my-app

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}\
      - name: Install project
        run: npm install

      - run: git config --global user.email "nathanzjyin@gmail.com"
      - run: git config --global user.name "Nathan Yin"
      - name: Deploy project
        run: npm run deploy